### ISSUE TITLE
missing file moco.builder.py

### ISSUE THREAD

**Issue by stevehuanghe** [tinapan-pt/VideoMoCo#4]
Hi,

Thanks for the interesting paper. While I was trying to run the code, I found that in `train.py` you have `import moco.builder`, which is not present under the `moco` folder. Would you please consider adding it back to the respository?

Best,
Steve

**Comment by shoutOutYangJie** [comment]
Why do you delete it?

**Comment by tianfr** [comment]
Last month I sent an email to the author and asked 2 questions about the code in moco.builder.py. One of the two seems serious, because I found **the gradient of Gnet is always NONE by using the implementation of moco.builder.py**. The next day after sending the email the author deleted the code and there are no updates after that.
Maybe the author is too busy and we need patience.
Here is the screenshot of the email:
![image](https://user-images.githubusercontent.com/44290909/124579372-a082b480-de81-11eb-968e-9b8661f4f3aa.png)

**Comment by tianfr** [comment]
> Last month I sent an email to the author and asked 2 questions about the code in moco.builder.py. One of the two seems serious, because I found **the gradient of Gnet is always NONE by using the implementation of moco.builder.py**. The next day after sending the email the author deleted the code and there are no updates after that.
> Maybe the author is too busy and we need patience.
> Here is the screenshot of the email:
> ![image](https://user-images.githubusercontent.com/44290909/124579372-a082b480-de81-11eb-968e-9b8661f4f3aa.png)

maybe this could answer your question @shoutOutYangJie

**Comment by tinapan-pt** [comment]
After receiving the email, I realized that the version I uploaded was wrong which missed a self-defining gradient backpropagation function, so I deleted it. I'm sorry to forget about it because I was busy with the graduation project at school some time ago. And I will release the new version as soon as possible!
